// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwagerAppV1._1.Model;

#nullable disable

namespace SwagerAppV1._1.Data.Migrations
{
    [DbContext(typeof(SwagerContext))]
    [Migration("20220822205425_cretedatabase")]
    partial class cretedatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SwagerAppV1._1.Model.Groups", b =>
                {
                    b.Property<int>("IdGrupe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdGrupe");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SwagerAppV1._1.Model.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdGrupe")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Users")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdGrupe");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SwagerAppV1._1.Model.Users", b =>
                {
                    b.HasOne("SwagerAppV1._1.Model.Groups", "Group")
                        .WithMany("User")
                        .HasForeignKey("IdGrupe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SwagerAppV1._1.Model.Groups", b =>
                {
                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
